[workspace]
resolver = "2"
members = [
    "geth-engine",
    "geth-mikoshi",
    "geth-repl",
    "geth-client",
    "geth-common",
    "geth-consensus",
    "geth-domain",
    "geth-client-tests",
    "geth-node",
]
