[package]
name = "geth-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.20"
tonic = "0.8"
prost = "0.11"
prost-types = "0.11"
prost-derive = "0.11"
byteorder = "1"

[build-dependencies]
tonic-build = "0.8"
