[package]
name = "geth-node"
version = "0.1.0"
edition = "2021"

[dependencies.geth-engine]
path = "../geth-engine"

[dependencies.tokio]
version = "1.20"
features = ["full"]

[dependencies]
clap = "*"
eyre = "0.6"
